# Generated by Django 4.0.1 on 2023-12-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madridevents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='events',
            table='events',
        ),
    ]
